<option value="0">null</option>
<option value="1">Jammu</option>
<option value="2">chandigarh</option>
<option value="3">jaipur</option>
<option value="4">gandhi nagar</opton>
<option value="5">delhi</option>
<option value="6">lucknow</option>
<option value="7">patna</option>
<option value="8">ranchi</option>
<option value="9">kolkata</option>
<option value="10">shilong</option>
<option value="11">mumbai</option>
<option value="12">hyderabad</option>
<option value="13">amravati</option>
<option value="14">panji</option>
<option value="15">bangalore</option>
<option value="16">chennai</option>
<option value="17">thiruvananthapuram</option>
